Support rumtime js (#6)
* test that show bug (stringify non-string-key)
NoSuchMethodError: Class 'int' has no instance getter 'length'.

* json5: number keys should be quoted?

* fix bug: stringify non-string-keys
stringify(Map<int, dynamic>) cause exception

* more test to verify the bug actually gone

* Bump version

* add changelog

* remove dart:io for compatible with js
- what if we remove stderr only?