Fix bug: can not stringify object where their keys are not string (#3)
* test that show bug (stringify non-string-key)
NoSuchMethodError: Class 'int' has no instance getter 'length'.

* json5: number keys should be quoted?

* fix bug: stringify non-string-keys
stringify(Map<int, dynamic>) cause exception